version: "3"

services:
  pg14:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg14
    environment:
      PUID: 0
      PGID: 0
      TZ: Asia/Shanghai
      POSTGRES_USER: lerry
      POSTGRES_PASSWORD: password
    volumes:
      - /data/pg14/:/var/lib/postgresql/data/
    # ports:
    #   - "15432:5432"
    network_mode: "host"
    restart: unless-stopped
