version: "3"

services:
  pg15:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg15
    environment:
      PUID: 0
      PGID: 0
      TZ: Asia/Shanghai
      POSTGRES_USER: lerry
      POSTGRES_PASSWORD: password
    volumes:
      - /data/pg15/:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"
    network_mode: "host"
    restart: unless-stopped
